# Generated by Django 4.0.1 on 2022-01-06 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentmarks', '0002_delete_students_delete_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateTimeField(db_column='D-O-B')),
                ('father_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.FloatField(db_column='English')),
                ('tamil', models.FloatField(db_column='Tamil')),
                ('maths', models.FloatField(db_column='Maths')),
                ('science', models.FloatField(db_column='Science')),
                ('social', models.FloatField(db_column='Social')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmarks.students')),
            ],
        ),
    ]
