# Generated by Django 4.0.1 on 2022-01-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmarks', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='student',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
