# Generated by Django 4.0.1 on 2022-01-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentmarks', '0004_remove_subjects_student_delete_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsDetails',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateTimeField(db_column='D-O-B')),
                ('father_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Studentmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmarks.studentsdetails')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmarks.subjects')),
            ],
        ),
    ]
